export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const SET_SUCCESS_NOTIFICATION = 'SET_SUCCESS_NOTIFICATION';
export const SET_ERROR_NOTIFICATION = 'SET_ERROR_NOTIFICATION';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';